ArkEcosystem/deployer

app/app-explorer.sh, app/process-explorer.sh, app/process-node.sh, config/explorer-server.js
=> Use dist for explorer & run with forever

lib/dependencies.sh
=> Use dpkg install status to detect package installation

app/process-core.sh
The only way to stop or uninstall core was to pass in --network. This also had an impact when installing over the top of an existing installation since that would do an uninstall first. This PR fixes that.
=> fix: stop-core command required network parameter

README.md, app/app-core.sh, manifest.json, vagrant/setup.sh
Option in the CLI to output the passphrases generated from by the deployer, if available.
=> feat: output passphrase option

app/app-core.sh
There is a "bug" with the setup of core, where something in sqlite causes `yarn build` to fail. To get round this with deployer, we keep looping until the build is successful. In order to try and speed up the process, this PR now removes the yarn .cache folder to try and help alleviate the issue.
=> fix: yarn setup loop

CODEOWNERS
=> chore: create code owners

lib/utils.sh
This fixes issues with getting the box's IP if installed on a local machine (e.g. VM)
=> fix: getting ip for local machines

app/app-core.sh, app/config-core.sh, app/process-core.sh, manifest.json, packages/js-deployer/lib/builder/genesis-block.js
Updates to the CLI. Primarily, core 2.5
=> [WIP] refactor: core 2.5 & general fixes

app/app-explorer.sh
The build process of explorer has changed, this PR reflects it.
=> fix: no longer using build.js to build the explorer

packages/js-deployer/lib/builder/genesis-block.js, packages/js-deployer/yarn.lock
Fixes conflicts on https://github.com/ArkEcosystem/deployer/pull/107
=> fix: merge conflicts

packages/js-deployer/bin/deployer
=> fix: removal of unwanted fees from plugins file generation

app/app-core.sh, app/update-core.sh, packages/js-deployer/yarn.lock
=> chore: 2.6.11 bump

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.24 version of ARK core.
=> chore: 2.6.24 bump

packages/js-deployer/bin/deployer
Fix the missing vendorfieldLength property.
=> fix: missing vendorfield length

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.25 version of ARK core.
=> chore: bump to 2.6.25

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.30 version of ARK core.
=> chore: bump to 2.6.30

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.31 version of ARK core.
=> chore: bump to 2.6.31

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.37 version of ARK core.
=> chore: bump to 2.6.37

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.38 version of ARK core.
=> chore: bump to 2.6.38

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.39 version of ARK core.
=> chore: bump to 2.6.39

packages/js-deployer/bin/deployer
going over deployer and checking for discrepancies when comparing to the latest core version
=> refactor: exceptions file generation

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.42 version of ARK core.
=> chore: bump to 2.6.42

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.49 version of ARK core.
=> chore: bump to 2.6.49

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.52 version of ARK core.
=> chore: bump to 2.6.52

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.54 version of ARK core.
=> chore: bump to 2.6.54

app/app-core.sh, app/update-core.sh, packages/js-deployer/package.json, packages/js-deployer/yarn.lock
Update to 2.6.57 version of ARK core.
=> chore: bump to 2.6.57

app/app-explorer.sh
=> fix: use master branch for explorer

README.md
Fix incorrect Guide/Blog link in the README.
> _reported by Discord user: `Bombox`_
=> docs(readme): fix incorrect guide link

app/app-core.sh, app/update-core-relay.sh
What changes are being made? 
*Adding condition to ask user if they want to retry or not when core setup through yarn fail*
Why are these changes necessary? 
*To prevent infinite loop in case of core setup failure*
- [ x ] Tests _(if necessary)_
- [ x ] Ready to be merged
=> fix: prevent possible infinite loop with setup script
